drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    cash int,
    admin boolean,
    primary key (id)
);

create table product
(
    id   bigint generated by default as identity,
    name varchar(255),
    description varchar (255),
    remain int,
    price int,
    primary key (id)
);

